apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: xyz-app
spec:
  template:
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
        - name: xyz-app
          image: nginx
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: xyz-app
  strategy:
    type: RollingUpdate

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50