apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
spec: 
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
  replicas: 3
  selector:
    app: my-app